# Ustalamy z jakiego obrazu bazowego korzystamy
FROM ubuntu:20.04

# Ustawiamy strefę czasową - konieczne jest to aby przy instalacji
# javy nie było prośby o ustawienie strefy czasowej
ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Uruchamiamy zaktualizowanie system i instalację wymaganych pakietów
RUN apt update && apt upgrade -y && \
apt install -y \
git \
openjdk-14-jdk \
maven

# Budujemy aplikację w oparciu o repozytorim gitowe i przenosimy
# zbudowaną aplikację do odpowiedniego katalogu
# Na koniec usuwamy zbędne pliki
RUN mkdir /code && \
cd /code && \
git clone https://gitlab.com/DevNotes.it/java/springbootshoopinglist-demo.git . && \
mvn package && \
mkdir /opt/app && \
mv /code/target/DemoApp.jar /opt/app && \
cd / && \
rm -r /code


# Usuwamy zbędne aplikacje - nie potrzebujemy ich bo
# już skompilowaliśmy naszą aplikację
RUN apt remove -y \
git \
maven && \
apt clean && \
apt autoremove --purge && \
rm -rf /var/lib/apt/lists

EXPOSE 8080

# Ustalamy jaki katalog będzie domyślnym katalogiem roboczym
# po uruchomieniu kontenera, dzięki temu
WORKDIR /opt/app

CMD java -jar /opt/app/DemoApp.jar
